import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; 
import Header from "@/componentes/Header/Header"; 
import Footer from "@/componentes/Footer/Footer"; 
import Link from 'next/link'; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> 
        <nav>
          <ul>
            <li>
              <Link href="/produtos">Produtos</Link> {}
            </li>
            <li>
              <Link href="/tecnologias">Tecnologias</Link> {}
            </li>
          </ul>
        </nav>
        <main>{children}</main> 
        <Footer /> 
      </body>
    </html>
  );
}
